language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - windows

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: 
  cargo: true

script:
  - cargo build --verbose --all
  - cd tests\inputs
  - cargo run -- -v
  - cargo test --verbose --all