language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: 
  cargo: true

script:
  - cargo build --verbose --all
  - cargo test --verbose --all